# This is a basic workflow to help you get started with Actions

name: Django CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
  
    runs-on: ubuntu-latest
    outputs:
      customtag: ${{steps.tager.outputs.tag}}
    steps:
    - uses: actions/checkout@v2
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 12
        postgresql db: massdb
        postgresql user: mass
        postgresql password: password 
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./codes/requirements.txt
        pip install -r ./codes/requirements
      
    - name: Run Tests
      run: |
        python manage.py test
        python ./codes/manage.py migrate 
    

